### ISSUE TITLE
Invalid index when enabled = false

### ISSUE THREAD

**Issue by kdeyko** [lablabs/terraform-aws-eks-cluster-autoscaler#10]
Hi there!

Found a bug in the module:
When `enabled = false` and the module was never run on the cluster, we get this error during `terraform plan`:
```
Error: Invalid index

  on .terraform/modules/eks-cluster-autoscaler/argo.tf line 11, in locals:
  11:         "values" : data.utils_deep_merge_yaml.values[0].output
    |----------------
    | data.utils_deep_merge_yaml.values is empty tuple

The given key does not identify an element in this collection value.
```

I guess the reason is: in `argo.tf` you're trying to set `values` (line11) from data resource `data.utils_deep_merge_yaml.values`  that is being created **only** if `enabled = true` (`main.tf` line 25).

Terraform version 0.14.11 (also tried on 1.0.11).
```
module "eks-cluster-autoscaler" {
  source  = "lablabs/eks-cluster-autoscaler/aws"
  version = "1.6.1"
```

**Comment by dojci** [comment]
Hi @kdeyko, thank you for reporting issue, yes we are aware of this issue across many modules. We are going to provide fix asap.

**Comment by kdeyko** [comment]
Thanks!

**Comment by dojci** [comment]
Sorry for the delay, fixed in https://github.com/lablabs/terraform-aws-eks-cluster-autoscaler/pull/12.
