### ISSUE TITLE
feature: Allow replacement of default iam policy

### ISSUE THREAD

**Issue by mathe-matician** [lablabs/terraform-aws-eks-cluster-autoscaler#16]
### Summary

There doesn't seem to be functionality to replace the default policy that is included with this provider:

https://github.com/lablabs/terraform-aws-eks-cluster-autoscaler/blob/8990dc80cfb1d6ce6770c7353c074f41b45c1f25/iam.tf#L5-L30

It would be great if you could set `irsa_policy_enabled = false` and then add your own policy via `irsa_additional_policies` or some other mechanism. For example, I'd like to swap the default policy out to use the [minimal iam permission policy](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/cloudprovider/aws/README.md#minimal-iam-permissions-policy).

### Issue Type

Feature Idea

**Comment by jaygridley** [comment]
Hello @mathe-matician, we have shipped an addon update that should address your use-case. Please, let me know if it worked for you.
