### ISSUE TITLE
Support TF 0.14.x

### ISSUE THREAD

**Issue by whume** [lablabs/terraform-aws-eks-cluster-autoscaler#3]
I think I am hitting this bug in the modules due to the use of the dynamic providers but I cannot test to confirm since the modules do not support Terraform 0.14. Can we add support for that?

hashicorp/terraform-provider-helm#476

**Comment by dojci** [comment]
Sorry for the delay, terraform 0.14 is now supported #4 (release [v1.3.0](https://github.com/lablabs/terraform-aws-eks-cluster-autoscaler/releases/tag/v1.3.0))
